apiVersion: v1
kind: Service
metadata:
  name: ncps
  labels:
    app.kubernetes.io/name: ncps
    app.kubernetes.io/part-of: agents
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8501"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ncps
  ports:
    - name: http
      port: 8501
      targetPort: 8501

